- name: "PrivateAppsyncEndpoint"
  authenticationType: AMAZON_COGNITO_USER_POOLS
  schema:
    - appsync/schemas/todo.graphql
  caching:
    behavior: FULL_REQUEST_CACHING
    ttl: 3600
    atRestEncryption:
    transitEncryption:
    type: "T2_SMALL"
  userPoolConfig:
    defaultAction: ALLOW
    userPoolId: !Ref ExampleUserPool
  logConfig:
    loggingRoleArn: { Fn::GetAtt: [AppSyncLoggingServiceRole, Arn] }
    level: ERROR
    excludeVerboseContent: false
  mappingTemplatesLocation: appsync/resolvers
  mappingTemplates:
    - ${file(./appsync/mappingtemplates.yml)}
  dataSources:
    - ${file(./appsync/datasources.yml)}
